spring.application.name=learn-spring-boot
server.port=8081
#logging.level.org.springframework=DEBUG
# trace, debug, info, warning,  error, off

spring.profiles.active=dev


management.endpoints.web.exposure.include=*